# -*- coding: utf-8 -*-
"""TITANIC PROJECT PLOTLY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uBE05f67RlJj_iYz44m78VjexXGisCPk
"""

import pandas as pd

df = pd.read_csv("https://gist.githubusercontent.com/fyyying/4aa5b471860321d7b47fd881898162b7/raw/6907bb3a38bfbb6fccf3a8b1edfb90e39714d14f/titanic_dataset.csv")
df

df.info()

import plotly.express as px


df['Age'].fillna(df['Age'].median(), inplace=True)
df['Fare'].fillna(df['Fare'].median(), inplace=True)
df['Cabin'] = df['Cabin'].notnull().astype(int)

df['Embarked'].fillna(df['Embarked'].mode(), inplace=True)
df.Embarked.value_counts()

df.Cabin

df.describe()

print(df.groupby('Sex')['Survived'].mean())
print(df.groupby('Pclass')['Survived'].mean())
print(df.groupby('Embarked')['Survived'].mean())

fig = px.histogram(df, x='Age', color='Survived', title='Age Distribution by Survival')
fig.show()

fig = px.bar(df.groupby('Pclass')['Survived'].mean().reset_index(),
             x='Pclass', y='Survived',
             title='Survival Rate by Ticket Class',
             labels={'Survived': 'Survival Rate'})
fig.show()

survival_rate_by_sex = df.groupby('Sex')['Survived'].mean().reset_index()
survival_rate_by_sex['SurvivalRatePercentage'] = (survival_rate_by_sex['Survived'] * 100).round(2).astype(str) + '%'
survival_rate_by_sex
fig = px.bar(survival_rate_by_sex,x='Sex',y='Survived',title="survival rate by sex",labels={'Survived': 'Survival Rate'},text="SurvivalRatePercentage")
fig.show()

fig.update_traces(textposition='outside')
fig.show()

pd.qcut?

df['FareQuartile']= pd.qcut(df['Fare'],4,labels=['Lowest', 'Lower-Middle', 'Upper-Middle', 'Highest'])
df[['Fare','FareQuartile']]

# Plotting survival rate by fare quartile
fig_fare = px.bar(df.groupby('FareQuartile')['Survived'].mean().reset_index(),
                  x='FareQuartile', y='Survived', text='Survived',
                  title='Survival Rate by Fare Quartile',
                  labels={'Survived': 'Survival Rate'})

fig_fare.show()

fig_fare.update_traces(texttemplate='%{text:.2%}', textposition='outside')
fig_fare.update_layout(yaxis_tickformat='.2%')

# Create age groups for better visualization
df['AgeGroup'] = pd.cut(df['Age'], bins=[0, 12, 18, 60, 100], labels=['Child', 'Teen', 'Adult', 'Senior'])

# Plotting survival rate by age group
fig_age = px.bar(df.groupby('AgeGroup')['Survived'].mean().reset_index(),
                 x='AgeGroup', y='Survived', text='Survived',
                 title='Survival Rate by Age Group',
                 labels={'Survived': 'Survival Rate'})
fig_age.update_traces(texttemplate='%{text:.2%}', textposition='outside')
fig_age.update_layout(yaxis_tickformat='.2%')
fig_age.show()

import pandas as pd
import plotly.express as px

# Assuming 'df' is your DataFrame and it has been cleaned appropriately
df['AgeGroup'] = pd.cut(df['Age'], bins=[0, 12, 18, 60, 100], labels=['Child', 'Teen', 'Adult', 'Senior'])

# Grouping by AgeGroup to calculate both count and mean survival rate
age_group_stats = df.groupby('AgeGroup').agg(Total=('Survived', 'count'),
                                             SurvivalRate=('Survived', 'mean')).reset_index()

# Convert the survival rate to a percentage for readability
age_group_stats['SurvivalRate'] = (age_group_stats['SurvivalRate'] * 100).round(2)

# Plotting
fig = px.bar(age_group_stats, x='AgeGroup', y='Total', text='Total',
             title='Total Passengers and Survival Rate by Age Group')

# Add another Y axis to show the survival rate
fig.add_scatter(x=age_group_stats['AgeGroup'], y=age_group_stats['SurvivalRate'],
                mode='lines+markers+text', text=age_group_stats['SurvivalRate'],
                name='Survival Rate (%)', textposition="top center")

# Updating layout to have a secondary y-axis for the survival rate
fig.update_layout(yaxis=dict(title='Total Number of Passengers'),
                  yaxis2=dict(title='Survival Rate (%)', overlaying='y', side='right'))

# Show the figure
fig.show()

print(df['AgeGroup'].value_counts())
print(df['AgeGroup'][df['Survived']==1].value_counts())

# Calculate the number of survivors per age group
survivors_per_age_group = df['AgeGroup'][df['Survived'] == 1].value_counts().reset_index()

survivors_per_age_group.columns = ['AgeGroup', 'Survivors']
survivors_per_age_group
# # Merge this with the existing age_group_stats DataFrame
age_group_stats = age_group_stats.merge(survivors_per_age_group, on='AgeGroup', how='left')

# Replace NaN values with 0 for age groups with no survivors (if any)
age_group_stats['Survivors'].fillna(0, inplace=True)
age_group_stats

import plotly.graph_objects as go

# Create figure with secondary y-axis
fig = go.Figure()

# Add bar for total number of passengers
fig.add_trace(go.Bar(
    x=age_group_stats['AgeGroup'],
    y=age_group_stats['Total'],
    name='Total Passengers',
    text=age_group_stats['Total'],
    marker_color='indianred'
))

# Add bar for number of survivors
fig.add_trace(go.Bar(
    x=age_group_stats['AgeGroup'],
    y=age_group_stats['Survivors'],
    name='Survivors',
    text=age_group_stats['Survivors'],
    marker_color='lightseagreen'
))

# Here we adjust the layout to display the bars side by side
fig.update_layout(
    barmode='group', # This makes the bars grouped
    title_text='Total Passengers and Survivors by Age Group',
    xaxis_title="Age Group",
    yaxis_title="Number of Passengers",
    legend_title="Legend"
)

# Show the figure
fig.show()